[package]
name = "rust-oop"
version = "0.1.0"
authors = ["khmhmm <matvey.zaharov@satellite-soft.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oop-prelude = { path = "./oop-prelude" }
